name: upload to Kattis
on: [push]
jobs:
  Upload-to-Kattis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:    
          cache: 'pip'
      - run: pip install -r requirements.txt
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            
            echo "Do something with this ${changed_file}"
            echo "${{secrets.KATTIS_USERNAME}}"
            python3 .github/scripts/submit.py ${changed_file} -u ${{secrets.KATTIS_USERNAME}} -k ${{secrets.KATTIS_TOKEN}}
          done
