name: upload to Kattis
on: [push]
jobs:
  Upload-to-Kattis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          $valid = $(python3 /.github/scripts/get_valid_files.py ${{ steps.files.outputs.all }})
          for valid_file in $valid; do
            echo "Do something with this ${valid_file}"
            #python3 /.github/scripts/submit.py ${changed_file} -u ${{secrets.KATTIS_USERNAME}} -k ${{secrets.KATTIS_TOKEN}}
          done
