name: upload to Kattis
on: [push]
env:
  PROBLEM_ID:
jobs:
  Upload-to-Kattis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: print
        run: |
          echo '${{ steps.files.outputs.added_modified }}'
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done